<?php 

/**
 * Implements hook_theme().
 **/
function bilimauth_theme($existing, $type, $theme, $path) {
  return [
    'user_prehome' => [
      'variables' => ['intro' => '', 'loginForm' => [],]
    ],
    'page_prehome' => [
      'variables' => ['intro' => '', 'content' => []],
    ],
    'page_customerhome' => [
      'variables' => ['intro' => '', 'content' => []],
    ],
    'page_domainview' => [
      'variables' => ['intro' => '', 'content' => []],
    ]
  ];
}

function bilimauth_page_attachments_alter(&$page){
  $path = $current_path = \Drupal::service('path.current')->getPath();
  if($path == '/node') {
    $page['#attached']['library'][] = 'my-theme/my-library';
  }
}

/**
 * Implements hook_form_alter().
 **/
function bilimauth_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    global $user;
    switch ($form_id) {
        // login form 
        case 'user_login_form':
        break;
        default:
        break;
    }
}