import { TemplateCategory } from "types";
import { TemplateMenu, TemplateType, CourseDisplay, ElementType } from "editor-constants";

const categoryies: TemplateCategory[] = [
  {
    id: "1",
    name: "top",
    description: "top",
    type: TemplateType.Category,
    menu: TemplateMenu.Left,
    order: "1",
    info: "",
    helpurl: "",
    children: [
      {
        id: "21",
        name: "Header",
        description: "Header",
        type: TemplateType.Category,
        menu: TemplateMenu.Left,
        order: "1",
        info: "",
        helpurl: "",
        children: [],
      },
      {
        id: "22",
        name: "Objective",
        description: "Objective",
        type: TemplateType.Category,
        menu: TemplateMenu.Left,
        order: "2",
        info: "",
        helpurl: "",
        children: [
          {
            id: "221",
            name: "Comparison",
            description: "Comparison",
            type: TemplateType.Category,
            menu: TemplateMenu.Left,
            order: "1",
            info: "",
            helpurl: "",
            children: [],
          },
        ],
      },
      {
        id: "23",
        name: "Lead",
        description: "Objective",
        type: TemplateType.Category,
        menu: TemplateMenu.Left,
        order: "3",
        info: "",
        helpurl: "",
        children: [
          {
            id: "231",
            name: "Comparison",
            description: "Comparison",
            type: TemplateType.Category,
            menu: TemplateMenu.Left,
            order: "1",
            info: "",
            helpurl: "",
            children: [
              {
                id: "2311",
                name: "Simple",
                description: "Simple",
                type: TemplateType.Category,
                menu: TemplateMenu.Tab,
                order: "1",
                info: "",
                helpurl: "",
                children: [],
              },
              {
                id: "2312",
                name: "Interaction",
                description: "Interaction",
                type: TemplateType.Category,
                menu: TemplateMenu.Tab,
                order: "2",
                info: "",
                helpurl: "",
                children: [
                  {
                    id: "23121",
                    name: "Group 1",
                    description: "Group 1",
                    type: TemplateType.Category,
                    menu: TemplateMenu.Inline,
                    order: "1",
                    info: "",
                    helpurl: "",
                    children: [],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "main",
    description: "main",
    type: TemplateType.Category,
    menu: TemplateMenu.Left,
    order: "2",
    info: "",
    helpurl: "",
    children: [
      {
        id: "21",
        name: "Text",
        description: "Text",
        type: TemplateType.Category,
        menu: TemplateMenu.Left,
        order: "3",
        info: "",
        helpurl: "",
        children: [
          {
            id: "211",
            name: "c01",
            description: "c01",
            type: TemplateType.Template,
            order: "1",
            framework: {},
            displays: [CourseDisplay.Desktop],
            scopes: [ElementType.Screen],
            contexts: [],
            structureContexts: [],
            themes: [],
            thumbnailLight: "",
            thumbnailDark: "",
            html: "",
            htmlNode: "",
            info: "",
            interaction: false,
            switchable: false,
            variants: [],
            warning: "",
          },
        ],
      },
      {
        id: "22",
        name: "Media",
        description: "Media",
        type: TemplateType.Category,
        menu: TemplateMenu.Left,
        order: "1",
        info: "",
        helpurl: "",
        children: [
          {
            id: "221",
            name: "c01",
            type: TemplateType.Template,
            description: "c01",
            order: "1",
            framework: {},
            displays: [CourseDisplay.Desktop],
            scopes: [ElementType.Screen],
            contexts: [],
            structureContexts: [],
            themes: [],
            thumbnailLight: "",
            thumbnailDark: "",
            html: "",
            htmlNode: "",
            info: "",
            interaction: false,
            switchable: false,
            variants: [],
            warning: "",
          },
        ],
      },
      {
        id: "23",
        name: "Lead",
        description: "Objective",
        type: TemplateType.Category,
        menu: TemplateMenu.Left,
        order: "2",
        info: "",
        helpurl: "",
        children: [
          {
            id: "231",
            name: "c01",
            type: TemplateType.Template,
            description: "c01",
            order: "1",
            framework: {},
            displays: [CourseDisplay.Desktop],
            scopes: [ElementType.Screen],
            contexts: [],
            structureContexts: [],
            themes: [],
            thumbnailLight: "",
            thumbnailDark: "",
            html: "",
            htmlNode: "",
            info: "",
            interaction: false,
            switchable: false,
            variants: [],
            warning: "",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "misc",
    description: "misc",
    type: TemplateType.Category,
    menu: TemplateMenu.Left,
    order: "3",
    info: "",
    helpurl: "",
    children: [],
  },
];

export default categoryies;
