import { Template, TemplateVariant, TemplateCategory } from "types";
import { TemplateType, ElementType, TemplateMenu, CourseDisplay } from "editor-constants";

export const variants: TemplateVariant[] = [
  {
    id: "1",
    name: "c01b",
    type: TemplateType.Template,
    description: "c01b",
    order: "1",
    thumbnailDark: "./templates/c01b-dark.jpg",
    thumbnailLight: "./templates/c01b.jpg",
    html: "<div></div>",
    htmlNode: "./templates/template c01b.html",
    info: "",
    warning: null,
  },
  {
    id: "2",
    name: "c01c",
    type: TemplateType.Template,
    description: "c01c",
    order: "2",
    thumbnailDark: "./templates/c01c-dark.jpg",
    thumbnailLight: "./templates/c01c.jpg",
    html: "",
    htmlNode: "./templates/template c01c.html",
    info: "",
    warning: null,
  },
  {
    id: "1",
    name: "c01d",
    type: TemplateType.Template,
    description: "c01d",
    order: "3",
    thumbnailDark: "./templates/c01d-dark.jpg",
    thumbnailLight: "./templates/c01d.jpg",
    html: "",
    htmlNode: "./templates/template c01d.html",
    info: "",
    warning: null,
  },
];

export const template1: Template = {
  id: "1",
  name: "c01",
  type: TemplateType.Template,
  description: "c01",
  thumbnailDark: "./templates/c01a-dark.jpg",
  thumbnailLight: "./templates/c01a.jpg",
  html: "",
  htmlNode: "./templates/template c01a.html",
  framework: {},
  scopes: [ElementType.PartPage],
  displays: [CourseDisplay.FullResponsive],
  contexts: [],
  structureContexts: [],
  themes: [],
  interaction: false,
  switchable: false,
  order: "1",
  variants: variants,
  info: "",
  warning: "",
};

export const template2: Template = {
  id: "2",
  name: "c02",
  type: TemplateType.Template,
  description: "c02",
  thumbnailDark: "./templates/c02a-dark.jpg",
  thumbnailLight: "./templates/c02a.jpg",
  html: "",
  htmlNode: "./templates/template c02a.html",
  framework: {},
  scopes: [ElementType.PartPage],
  displays: [CourseDisplay.FullResponsive],
  contexts: [],
  structureContexts: [],
  themes: [],
  interaction: false,
  switchable: false,
  order: "2",
  variants: variants,
  info: "You can use this template for many purposes",
  warning: "You can use this template for many purposes",
};

const templates = [template1, template2];

export const simpleCategory1: TemplateCategory = {
  id: "234",
  name: "Text",
  description: "Text",
  type: TemplateType.Category,
  order: "1",
  menu: TemplateMenu.Left,
  info: "sample info here",
  children: templates,
  helpurl: "",
};

export const simpleCategory2: TemplateCategory = {
  id: "344",
  name: "Media",
  description: "Media",
  type: TemplateType.Category,
  order: "1",
  menu: TemplateMenu.Left,
  info: "",
  children: templates,
  helpurl: "",
};

export const tabCategory: TemplateCategory = {
  id: "111",
  name: "Browse",
  description: "Browse",
  type: TemplateType.Category,
  order: "1",
  menu: TemplateMenu.Left,
  info: "",
  helpurl: "",
  children: [
    {
      id: "1",
      name: "Simple",
      description: "Simple",
      type: TemplateType.Category,
      order: "1",
      menu: TemplateMenu.Tab,
      info: "",
      helpurl: "",
      children: templates,
    },
    {
      id: "2",
      name: "Interaction",
      description: "Interaction",
      type: TemplateType.Category,
      order: "2",
      menu: TemplateMenu.Tab,
      info: "",
      helpurl: "",
      children: templates,
    },
  ],
};

export const groupCategroy: TemplateCategory = {
  id: "21",
  name: "Browse",
  description: "Browse",
  type: TemplateType.Category,
  order: "1",
  menu: TemplateMenu.Left,
  info: "",
  helpurl: "",
  children: [
    {
      id: "12",
      name: "Group 1",
      description: "Group 1",
      type: TemplateType.Category,
      order: "1",
      menu: TemplateMenu.Inline,
      info: "",
      helpurl: "",
      children: templates,
    },
    {
      id: "21",
      name: "Group 2",
      description: "Group 2",
      type: TemplateType.Category,
      order: "2",
      menu: TemplateMenu.Inline,
      info: "",
      helpurl: "",
      children: templates,
    },
  ],
};

export const tabGroupCategory: TemplateCategory = {
  id: "31",
  name: "Browse",
  description: "Browse",
  type: TemplateType.Category,
  order: "1",
  menu: TemplateMenu.Left,
  info: "",
  helpurl: "",
  children: [
    {
      id: "32",
      name: "Simple",
      description: "Simple",
      type: TemplateType.Category,
      order: "1",
      menu: TemplateMenu.Tab,
      info: "",
      helpurl: "",
      children: groupCategroy.children,
    },
    {
      id: "33",
      name: "Interaction",
      description: "Interaction",
      type: TemplateType.Category,
      order: "2",
      menu: TemplateMenu.Tab,
      info: "",
      helpurl: "",
      children: groupCategroy.children,
    },
  ],
};
